# Generated by Django 4.2.4 on 2025-02-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Streaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_streaming', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('Date_streaming', models.DateField()),
                ('Type_streaming', models.CharField(default='film', max_length=50)),
                ('Image_streaming', models.ImageField(upload_to='Telechargement')),
                ('video_streaming', models.ImageField(upload_to='Telechargement')),
            ],
        ),
    ]
