# Generated by Django 4.2.4 on 2025-02-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Streaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streaming',
            name='video_streaming',
            field=models.FileField(upload_to='Telechargement'),
        ),
    ]
