# Generated by Django 4.2.4 on 2025-02-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Streaming', '0002_alter_streaming_video_streaming'),
    ]

    operations = [
        migrations.AddField(
            model_name='streaming',
            name='Acteurs',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='streaming',
            name='Duree_streaming',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='streaming',
            name='Genre',
            field=models.CharField(default='Science-fiction | Drame | Action', max_length=255),
        ),
        migrations.AddField(
            model_name='streaming',
            name='Note',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='streaming',
            name='Realisateur',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
