# Generated by Django 4.2.4 on 2025-02-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Streaming', '0003_streaming_acteurs_streaming_duree_streaming_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streaming',
            name='Date_streaming',
            field=models.DateField(blank=True, null=True),
        ),
    ]
