# Generated by Django 4.2.4 on 2025-03-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Streaming', '0004_alter_streaming_date_streaming'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=55)),
                ('Message', models.TextField(max_length=255)),
            ],
        ),
    ]
