# Generated by Django 4.2.4 on 2025-03-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Streaming', '0005_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streaming',
            old_name='video_streaming',
            new_name='Video_streaming',
        ),
        migrations.AddField(
            model_name='streaming',
            name='Prix_streaming',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='streaming',
            name='Salle_streaming',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
