# Generated by Django 4.2.4 on 2025-04-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Streaming', '0006_rename_video_streaming_streaming_video_streaming_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streaming',
            name='Image_streaming',
        ),
        migrations.RemoveField(
            model_name='streaming',
            name='Video_streaming',
        ),
        migrations.AddField(
            model_name='streaming',
            name='image_url',
            field=models.URLField(default=0, max_length=500, verbose_name="Lien de l'image"),
            preserve_default=False,
        ),
    ]
