# Generated by Django 4.2.4 on 2025-02-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='places',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='film',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Film',
        ),
    ]
