# Generated by Django 4.2.4 on 2025-03-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0002_remove_reservation_places_alter_reservation_film_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('film', models.CharField(max_length=100)),
                ('salle', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=20)),
                ('date_diffusion', models.CharField(max_length=20)),
                ('email_reception', models.EmailField(max_length=254)),
            ],
        ),
    ]
